### ISSUE TITLE
Palm compatibility.

### ISSUE THREAD

**Issue by andrey-canon** [eduNEXT/drydock#40]
## Description
Since  Palm release was cut on April 11th 2023, I would like to know if there is a drydock date release for Palm version. Thanks

**Comment by jfavellar90** [comment]
@andrey-canon thanks for your question. Drydock depends heavily on Tutor, and the new Tutor release supporting Palm will be available the same day as the official release of the OpenedX Palm version (ETA is 09 June I think). Once this release happens, we'll prioritize this task. For now, I would not commit to any specific date, however, we expect that Drydock support for Palm is ready one month later (2 Atlas sprints) in the worst-case scenario. For the Olive release, the Pearson team joined this effort to speed it up, so don't hesitate to ping me up if you want to contribute.

**Comment by andrey-canon** [comment]
Thanks
